### ISSUE TITLE
Music dont play / expired discord invite

### ISSUE THREAD

**Issue by adriancpp** [Furq07/Vinyls#2]
I wanted to ask on discord, but invite link is outdated.
i have 1.21.1 paper server with geyser, i go through all Installation Steps, but when i entered on the server, music disc dont play.
No errors on konsole, also i tried my .ogg file to add just to replace some vanilla music disc and it played my new music.
But when i use /vinyls give command and put disc (which looks proper) it is silent in jukebox.
Resourcepack for sure is loaded properly.

ogg file is ofc in mono format,
i put needed files into source_files folder
i join from premium java fabric 1.21.1 client - as /op

**Comment by Furqit** [comment]
I will test it out myself and let you know, thanks for reporting.

**Comment by Frost-4X** [comment]
Bumping this, I came to make the exact same issue. Discord doesn't work, music isn't playing.

**Comment by Furqit** [comment]
This has been fixed, get the latest version from modrinth: https://modrinth.com/plugin/vinyls
